version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--entrypoints.web.address=:8080"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--api.dashboard=true"
    ports:
      - "8080:8080"
    volumes:
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    restart: unless-stopped
    networks:
      - localweb

networks:
  localweb:
    external: true
