version: '3'

services:
  vault:
    image: hashicorp/vault:1.13.3
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    depends_on:
      - consul
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault-config.json
    restart: unless-stopped
    networks:
      - vault-consul

  consul:
    image: hashicorp/consul:1.15.4
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - ./consul/config:/consul/config
    command: consul agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0 -config-dir=/consul/config
    restart: unless-stopped
    networks:
      - vault-consul

networks:
  vault-consul:
    driver: bridge